name: Bug report
description: Create a report to help us improve
assignee: ["digicatapult/software-engineering"]
labels: ["bug"]
body:
  - type: textarea
    id: ticket-id
    attributes:
      label: Ticket ID
      description:  Ticket ID number for this bug (if applicable)
    validations:
      required: false
  - type: checkboxes
    id: checked-faq
    attributes:
      label: I have checked the FAQ for common solutions
    validations:
      required: true
  - type: checkboxes
    id: checked-issues
    attributes:
      label: I have checked this issue hasn't already been reported
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the bug
      description: Tell us what bug you encountered and what should have happened
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce the bug
      description: Tell us how to reproduce this bugs, in as much detail as possible
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
      description: What behaviour did you expect to happen when this bug occured?
    validations:
      required: true
  - type: textarea
    id: actual-behaviour
    attributes:
      label: What actually happened?
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: What version of the software were you running?
      description: You can get this information from copy and pasting the version on the home page or via package.json. Also, please include the OS and what version of the OS you're running.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Any other additional information?
      description: Any additional information, configuration or data that might be necessary to reproduce the issue.
    validations:
      required: false