name: Synchronise all PR versions

on:
  push:
    branches: $default-branch

permissions:
  contents: write
  pull-requests: write

jobs:
  synchronise-trunk-version-npm:
    uses: digicatapult/shared-workflows/.github/workflows/synchronise-trunk-version-npm.yml@main
    with:
      trunk-branch: $default-branch
    secrets:
      bot-id: ${{ secrets.BOT_ID }}
      bot-key: ${{ secrets.BOT_KEY }}
